### ISSUE TITLE
Remove language from POEditor

### ISSUE THREAD

**Issue by FTno** [sunilpaulmathew/sCommon#1]
Yesterday I added and translated some strings in 'Norwegian Bokmål'. I see now that you have added 'Norwegian'. As this is in practice the same, I ask you to remove 'Norwegian'. It would be meaningless if someone started to translate this.

**Comment by sunilpaulmathew** [comment]
@FTno 
Okay, It's done. However, if both are almost same, may I merge the already existing one to your version (which is of-course made by you for sNotz).

**Comment by FTno** [comment]
I didn't look into the content of 'Norwegian' (that you added), but if some strings were translated there that are not translated in 'Norwegian Bokmål' then it makes sense to merge (I didn't translate the Permissions strings).
I didn't think of the content then I wrote "in practice the same", it's just meaningless to have both of them in the POEditor, and both language files would have to be imported to the same 'values-nb' folder!

**Comment by sunilpaulmathew** [comment]
> ge files would have to b

You're perfectly right and I understand it. Only thing I was curious was whether both will go to same folder or not. Since you already mentioned that both will go to same place ('values-nb'), that too cleared. Btw, thanks a lot for helping me with translations.
& permissions are for other two apps. Feel free to leave it if it is not interesting for you :)
![Screenshot_20211119-142136](https://user-images.githubusercontent.com/15515387/142630215-55b4625c-cc7e-456a-ab4c-2a62969a6521.jpg)

**Comment by sunilpaulmathew** [comment]
@FTno 
Btw, is this correct?
```
<string name="language_nb" translatable="false">norsk</string>
```
Thanks

**Comment by FTno** [comment]
That should be fine.
